flags: {}
extra-deps:
- ansi-terminal-0.6.2.3
- ansi-wl-pprint-0.6.7.3
- colour-2.3.3
- dlist-0.7.1.2
- exceptions-0.8.0.2
- fgl-5.5.2.3
- graphviz-2999.18.0.2
- mtl-2.2.1
- optparse-applicative-0.12.0.0
- polyparse-1.11
- stm-2.4.4.1
- temporary-1.2.0.3
- text-1.2.2.0
- transformers-compat-0.4.0.4
- wl-pprint-text-1.1.0.4
resolver: ghc-7.10.3
